USE vaxapp;

INSERT INTO countrys (country, iso, continent, region) 
VALUES 
    ('Afghanistan','AF','Asia','South Asia'),
    ('Albania','AL','Europe','Balkan'),
    ('Algeria','DZ','Africa','North Africa'),
    ('American Samoa','AS','Oceania','Polynesia'),
    ('Andorra','AD','Europe','Western Europe'),
    ('Angola','AO','Africa','Central Africa'),
    ('Anguilla','AI','North America','Caribbean'),
    ('Antarctica','AQ','Antarctica','Antarctica'),
    ('Antigua and Barbuda','AG','North America','Caribbean'),
    ('Argentina','AR','South America','Southern South America'),
    ('Armenia','AM','Asia','Caucasus'),
    ('Aruba','AW','North America','Caribbean'),
    ('Australia','AU','Oceania','Australasia'),
    ('Austria','AT','Europe','Central Europe'),
    ('Azerbaijan','AZ','Asia','Caucasus'),
    ('Azores','A1','Europe','Atlantic Ocean'),
    ('Bahamas (The)','BS','North America','Caribbean'),
    ('Bahrain','BH','Asia','Arabia'),
    ('Bangladesh','BD','Asia','South Asia'),
    ('Barbados','BB','North America','Caribbean'),
    ('Belarus','BY','Europe','Eastern Europe'),
    ('Belgium','BE','Europe','Western Europe'),
    ('Belize','BZ','North America','Central America'),
    ('Benin','BJ','Africa','West Africa'),
    ('Bermuda','BM','North America','Northern America'),
    ('Bhutan','BT','Asia','South Asia'),
    ('Bolivia','BO','South America','Andean'),
    ('Bonaire','BQ','North America','Caribbean'),
    ('Bosnia and Herzegovina','BA','Europe','Balkan'),
    ('Botswana','BW','Africa','Southern Africa'),
    ('Brazil','BR','South America','Eastern South America'),
    ('British Indian Ocean Territory','IO','Africa','East Africa (Islands)'),
    ('Brunei','BN','Asia','South East Asia'),
    ('Bulgaria','BG','Europe','Balkan'),
    ('Burkina Faso','BF','Africa','West Africa'),
    ('Burundi','BI','Africa','East Africa'),
    ('Cambodia','KH','Asia','South East Asia'),
    ('Cameroon','CM','Africa','Central Africa'),
    ('Canada','CA','North America','Northern America'),
    ('Canary Islands','IC','Africa','North Africa (Islands)'),
    ('Cape Verde','CV','Africa','West Africa (Islands)'),
    ('Cayman Islands','KY','North America','Caribbean'),
    ('Central African Republic','CF','Africa','Central Africa'),
    ('Chad','TD','Africa','Central Africa'),
    ('Chile','CL','South America','Andean'),
    ('China','CN','Asia','East Asia'),
    ('Christmas Island (Australia)','CX','Oceania','Australasia'),
    ('Cocos (Keeling) Islands','CC','Oceania','Australasia'),
    ('Colombia','CO','South America','Northern South America'),
    ("Côte d'Ivoire",'CI','Africa','West Africa'),
    ('Comoros','KM','Africa','East Africa (Islands)'),
    ('Congo (Democratic Republic of the)','CD','Africa','Central Africa'),
    ('Congo (Republic of the)','CG','Africa','Central Africa'),
    ('Cook Islands','CK','Oceania','Polynesia'),
    ('Costa Rica','CR','North America','Central America'),
    ('Croatia','HR','Europe','Balkan'),
    ('Cuba','CU','North America','Caribbean'),
    ('Curaçao','CW','North America','Caribbean'),
    ('Cyprus','CY','Europe','Southern Europe'),
    ('Czech Republic','CZ','Europe','Central Europe'),
    ('Denmark','DK','Europe','Nordic'),
    ('Djibouti','DJ','Africa','East Africa'),
    ('Dominica','DM','North America','Caribbean'),
    ('Dominican Republic','DO','North America','Caribbean'),
    ('Easter Island','CL','Oceania','Polynesia'),
    ('Ecuador','EC','South America','Andean'),
    ('Egypt','EG','Africa','North Africa'),
    ('El Salvador','SV','North America','Central America'),
    ('Equatorial Guinea','GQ','Africa','Central Africa'),
    ('Eritrea','ER','Africa','East Africa'),
    ('Estonia','EE','Europe','Eastern Europe'),
    ('Eswatini (Swaziland)','SZ','Africa','Southern Africa'),
    ('Ethiopia','ET','Africa','East Africa'),
    ('Falkland Islands (Islas Malvinas)','FK','South America','Southern South America'),
    ('Faroe Islands','FO','Europe','Nordic'),
    ('Fiji','FJ','Oceania','Melanesia'),
    ('Finland','FI','Europe','Nordic'),
    ('France','FR','Europe','Western Europe'),
    ('French Guiana','GF','South America','The Guianas'),
    ('French Polynesia','PF','Oceania','Polynesia'),
    ('Gabon','GA','Africa','Central Africa'),
    ('Gambia','GM','Africa','West Africa'),
    ('Georgia','GE','Asia','Caucasus'),
    ('Germany','DE','Europe','Central Europe'),
    ('Ghana','GH','Africa','West Africa'),
    ('Gibraltar','GI','Europe','Southern Europe'),
    ('Greece','GR','Europe','Southern Europe'),
    ('Greenland','GL','North America','Northern America'),
    ('Grenada','GD','North America','Caribbean'),
    ('Guadeloupe','GP','North America','Caribbean'),
    ('Guam','GU','Oceania','Micronesia'),
    ('Guatemala','GT','North America','Central America'),
    ('Guinea','GN','Africa','West Africa'),
    ('Guinea-Bissau','GW','Africa','West Africa'),
    ('Guyana','GY','South America','The Guianas'),
    ('Haiti','HT','North America','Caribbean'),
    ('Honduras','HN','North America','Central America'),
    ('Hong Kong SAR','HK','Asia','East Asia'),
    ('Hungary','HU','Europe','Central Europe'),
    ('Iceland','IS','Europe','Nordic'),
    ('India','IN','Asia','South Asia'),
    ('Indonesia','ID','Asia','South East Asia'),
    ('Iran','IR','Asia','South Asia'),
    ('Iraq','IQ','Asia','West Asia'),
    ('Ireland','IE','Europe','Western Europe'),
    ('Israel','IL','Asia','Arabia'),
    ('Italy','IT','Europe','Southern Europe'),
    ('Jamaica','JM','North America','Caribbean'),
    ('Japan','JP','Asia','East Asia'),
    ('Jordan','JO','Asia','Arabia'),
    ('Kazakhstan','KZ','Asia','Central Asia'),
    ('Kenya','KE','Africa','East Africa'),
    ('Kiribati','KI','Oceania','Micronesia'),
    ('Kosovo','XK','Europe','Balkan'),
    ('Kuwait','KW','Asia','Arabia'),
    ('Kyrgyzstan','KG','Asia','Central Asia'),
    ('Laos','LA','Asia','South East Asia'),
    ('Latvia','LV','Europe','Eastern Europe'),
    ('Lebanon','LB','Asia','Arabia'),
    ('Lesotho','LS','Africa','Southern Africa'),
    ('Liberia','LR','Africa','West Africa'),
    ('Libya','LY','Africa','North Africa'),
    ('Liechtenstein','LI','Europe','Central Europe'),
    ('Lithuania','LT','Europe','Eastern Europe'),
    ('Luxembourg','LU','Europe','Western Europe'),
    ('Macau SAR','MO','Asia','East Asia'),
    ('Madagascar','MG','Africa','East Africa (Islands)'),
    ('Madeira Islands','M1','Africa','North Africa (Islands)'),
    ('Malawi','MW','Africa','East Africa'),
    ('Malaysia','MY','Asia','South East Asia'),
    ('Maldives','MV','Asia','South Asia'),
    ('Mali','ML','Africa','West Africa'),
    ('Malta','MT','Europe','Southern Europe'),
    ('Marshall Islands','MH','Oceania','Micronesia'),
    ('Martinique','MQ','North America','Caribbean'),
    ('Mauritania','MR','Africa','West Africa'),
    ('Mauritius','MU','Africa','East Africa (Islands)'),
    ('Mayotte','YT','Africa','East Africa (Islands)'),
    ('Mexico','MX','North America','Central America'),
    ('Micronesia (Federated States of)','FM','Oceania','Micronesia'),
    ('Moldova','MD','Europe','Eastern Europe'),
    ('Monaco','MC','Europe','Southern Europe'),
    ('Mongolia','MN','Asia','East Asia'),
    ('Montenegro','ME','Europe','Balkan'),
    ('Montserrat','MS','North America','Caribbean'),
    ('Morocco','MA','Africa','North Africa'),
    ('Mozambique','MZ','Africa','East Africa'),
    ('Myanmar (Burma)','MM','Asia','South East Asia'),
    ('Namibia','NA','Africa','Southern Africa'),
    ('Nauru','NR','Oceania','Micronesia'),
    ('Nepal','NP','Asia','South Asia'),
    ('Netherlands','NL','Europe','Western Europe'),
    ('New Caledonia','NC','Oceania','Melanesia'),
    ('New Zealand (Aotearoa)','NZ','Oceania','Australasia'),
    ('Nicaragua','NI','North America','Central America'),
    ('Niger','NE','Africa','West Africa'),
    ('Nigeria','NG','Africa','West Africa'),
    ('Niue','NU','Oceania','Polynesia'),
    ('Norfolk Island','NF','Oceania','Australasia'),
    ('North Korea','KP','Asia','East Asia'),
    ('North Macedonia','MK','Europe','Balkan'),
    ('Northern Mariana Islands','MP','Oceania','Micronesia'),
    ('Norway','NO','Europe','Nordic'),
    ('Oman','OM','Asia','Arabia'),
    ('Pakistan','PK','Asia','South Asia'),
    ('Palau','PW','Oceania','Micronesia'),
    ('Panama','PA','North America','Central America'),
    ('Papua New Guinea','PG','Oceania','Melanesia'),
    ('Paraguay','PY','South America','Eastern South America'),
    ('Peru','PE','South America','Andean'),
    ('Philippines','PH','Asia','South East Asia'),
    ('Pitcairn Islands','PN','Oceania','Polynesia'),
    ('Poland','PL','Europe','Nordic'),
    ('Portugal','PT','Europe','Southern Europe'),
    ('Puerto Rico','PR','North America','Caribbean'),
    ('Qatar','QA','Asia','Arabia'),
    ('Réunion','RE','Africa','East Africa (Islands)'),
    ('Romania','RO','Europe','Balkan'),
    ('Russia','RU','Europe','Eastern Europe'),
    ('Rwanda','RW','Africa','East Africa'),
    ('Saba','S1','North America','Caribbean'),
    ('Saint Barthélemy','BL','North America','Caribbean'),
    ('Saint Helena','H1','Africa','Atlantic Ocean'),
    ('Saint Kitts and Nevis','KN','North America','Caribbean'),
    ('Saint Lucia','LC','North America','Caribbean'),
    ('Saint Martin','MF','North America','Caribbean'),
    ('Saint Pierre and Miquelon','PM','North America','Northern America'),
    ('Saint Vincent and the Grenadines','VC','North America','Caribbean'),
    ('Samoa','WS','Oceania','Polynesia'),
    ('San Marino','SM','Europe','Southern Europe'),
    ('São Tomé and Príncipe','ST','Africa','Central Africa (Islands)'),
    ('Saudi Arabia','SA','Asia','Arabia'),
    ('Senegal','SN','Africa','West Africa'),
    ('Serbia','RS','Europe','Balkan'),
    ('Seychelles','SC','Africa','East Africa (Islands)'),
    ('Sierra Leone','SL','Africa','West Africa'),
    ('Singapore','SG','Asia','South East Asia'),
    ('Sint Eustatius','E1','North America','Caribbean'),
    ('Sint Maarten','SX','North America','Caribbean'),
    ('Slovakia','SK','Europe','Central Europe'),
    ('Slovenia','SI','Europe','Balkan'),
    ('Solomon Islands','SB','Oceania','Melanesia'),
    ('Somalia','SO','Africa','East Africa'),
    ('South Africa','ZA','Africa','Southern Africa'),
    ('South Georgia and the South Sandwich Islands','GS','Antarctica','Antarctica'),
    ('South Korea','KR','Asia','East Asia'),
    ('South Sudan','SS','Africa','East Africa'),
    ('Spain','ES','Europe','Southern Europe'),
    ('Sri Lanka','LK','Asia','South Asia'),
    ('Sudan','SD','Africa','North Africa'),
    ('Suriname','SR','South America','The Guianas'),
    ('Sweden','SE','Europe','Nordic'),
    ('Switzerland','CH','Europe','Central Europe'),
    ('Syria','SY','Asia','Arabia'),
    ('Taiwan','TW','Asia','East Asia'),
    ('Tajikistan','TJ','Asia','Central Asia'),
    ('Tanzania','TZ','Africa','East Africa'),
    ('Thailand','TH','Asia','South East Asia'),
    ('Timor-Leste (East Timor)','TL','Asia','South East Asia'),
    ('Togo','TG','Africa','West Africa'),
    ('Tokelau','TK','Oceania','Polynesia'),
    ('Tonga','TO','Oceania','Polynesia'),
    ('Trinidad and Tobago','TT','North America','Caribbean'),
    ('Tunisia','TN','Africa','North Africa'),
    ('Turkey','TR','Asia','West Asia'),
    ('Turkmenistan','TM','Asia','Central Asia'),
    ('Turks and Caicos Islands','TC','North America','Caribbean'),
    ('Tuvalu','TV','Oceania','Polynesia'),
    ('Uganda','UG','Africa','East Africa'),
    ('Ukraine','UA','Europe','Eastern Europe'),
    ('United Arab Emirates','AE','Asia','Arabia'),
    ('United Kingdom','GB','Europe','Western Europe'),
    ('United States','US','North America','Northern America'),
    ('Uruguay','UY','South America','Eastern South America'),
    ('Uzbekistan','UZ','Asia','Central Asia'),
    ('Vanuatu','VU','Oceania','Melanesia'),
    ('Vatican (The)','VA','Europe','Southern Europe'),
    ('Venezuela','VE','South America','Northern South America'),
    ('Vietnam','VN','Asia','South East Asia'),
    ('Virgin Islands (British)','VG','North America','Caribbean'),
    ('Virgin Islands (US)','VI','North America','Caribbean'),
    ('Wake Island','WK','Oceania','Micronesia'),
    ('Western Sahara','EH','Africa','North Africa'),
    ('Yemen','YE','Asia','Arabia'),
    ('Zambia','ZM','Africa','East Africa'),
    ('Zimbabwe','ZW','Africa','East Africa');

-- SELECT * FROM countrys;
