USE vaxapp;

INSERT INTO diseases (disease)
VALUES 
   ('Cholera'),
   ('Hepatitis A'),
   ('Hepatitis B'),
   ('Malaria'),
   ('Measels '),
   ('Meningitis'),
   ('Polio'),
   ('Rabies'),
   ('Typhoid'),
   ('Yellow'),
   ('Japanese Encephalitis'),
   ('Pneumonia'),
   ('Mumps'),
   ('Rubella'),
   ('Tetinus'),
   ('Diphtheria'),
   ('Pertussis '),
   ('Chickenpox (Varicella)'),
   ('Influenza'),
   ('HPV (Human Papillomavirus)'),
   ('Shingles (Herpes Zoster)'),
   ('Covid-19');

INSERT INTO recomendations(country_id, disease_id, priority)
VALUES
    ('Afghanistan', 2, 'most'),
    ('Afghanistan', 3, 'some'),
    ('Afghanistan', 4, 'some'),
    ('Afghanistan', 5, 'all'),
    ('Afghanistan', 7, 'all'),
    ('Afghanistan', 8, 'some'),
    ('Afghanistan', 9, 'most'),
    ('Argentina', 2, 'most'),
    ('Argentina', 3, 'some'),
    ('Argentina', 5, 'all'),
    ('Argentina', 8, 'some'),
    ('Argentina', 9, 'most'),
    ('Iceland', 2, 'some'),
    ('Iceland', 3, 'some'),
    ('Iceland', 5, 'all'),
    ('Iceland', 8, 'some'),
    ('India', 1, 'some'),
    ('India', 2, 'most'),
    ('India', 3, 'some'),
    ('India', 4, 'some'),
    ('India', 5, 'all'),
    ('India', 8, 'some'),
    ('India', 9, 'most'),
    ('Indonesia', 2, 'most'),
    ('Indonesia', 3, 'some'),
    ('Indonesia', 4, 'some'),
    ('Indonesia', 5, 'all'),
    ('Indonesia', 7, 'all'),
    ('Indonesia', 8, 'some'),
    ('Indonesia', 9, 'most'),
    ('Iran', 2, 'most'),
    ('Iran', 3, 'some'),
    ('Iran', 4, 'some'),
    ('Iran', 5, 'all'),
    ('Iran', 7, 'all'),
    ('Iran', 8, 'some'),
    ('Iran', 9, 'most'),
    ('Iraq', 1, 'some'),
    ('Iraq', 2, 'most'),
    ('Iraq', 3, 'some'),
    ('Iraq', 5, 'all'),
    ('Iraq', 8, 'some'),
    ('Iraq', 9, 'most'),
    ('Ireland', 2, 'some'),
    ('Ireland', 3, 'some'),
    ('Ireland', 5, 'all'),
    ('Ireland', 8, 'some'),
    ('Israel', 2, 'most'),
    ('Israel', 3, 'some'),
    ('Israel', 5, 'all'),
    ('Israel', 8, 'some'),
    ('Italy', 2, 'some'),
    ('Italy', 3, 'some'),
    ('Italy', 5, 'all'),
    ('Italy', 8, 'some'),
    ('Jamaica', 2, 'most'),
    ('Jamaica', 3, 'some'),
    ('Jamaica', 5, 'all'),
    ('Jamaica', 8, 'some'),
    ('Jamaica', 9, 'most'),
    ('Japan', 2, 'some'),
    ('Japan', 3, 'some'),
    ('Japan', 5, 'all'),
    ('Japan', 8, 'some'),
    ('Armenia', 2, 'most'),
    ('Armenia', 3, 'some'),
    ('Armenia', 5, 'all'),
    ('Armenia', 8, 'some'),
    ('Jordan', 2, 'most'),
    ('Jordan', 3, 'some'),
    ('Jordan', 5, 'all'),
    ('Jordan', 8, 'some'),
    ('Jordan', 9, 'most'),
    ('Kazakhstan', 2, 'most'),
    ('Kazakhstan', 3, 'some'),
    ('Kazakhstan', 5, 'all'),
    ('Kazakhstan', 8, 'some'),
    ('Kazakhstan', 9, 'most'),
    ('Kenya', 1, 'some'),
    ('Kenya', 2, 'most'),
    ('Kenya', 3, 'some'),
    ('Kenya', 4, 'some'),
    ('Kenya', 5, 'all'),
    ('Kenya', 8, 'some'),
    ('Kenya', 9, 'most'),
    ('Kiribati', 2, 'most'),
    ('Kiribati', 3, 'some'),
    ('Kiribati', 5, 'all'),
    ('Kiribati', 9, 'most'),
    ('Kosovo', 2, 'most'),
    ('Kosovo', 3, 'some'),
    ('Kosovo', 5, 'all'),
    ('Kosovo', 8, 'some'),
    ('Kuwait', 2, 'most'),
    ('Kuwait', 3, 'some'),
    ('Kuwait', 5, 'all'),
    ('Kuwait', 8, 'some'),
    ('Kuwait', 9, 'most'),
    ('Kyrgyzstan', 2, 'most'),
    ('Kyrgyzstan', 3, 'some'),
    ('Kyrgyzstan', 5, 'all'),
    ('Kyrgyzstan', 8, 'some'),
    ('Kyrgyzstan', 9, 'most'),
    ('Laos', 2, 'most'),
    ('Laos', 3, 'some'),
    ('Laos', 4, 'some'),
    ('Laos', 5, 'all'),
    ('Laos', 8, 'some'),
    ('Laos', 9, 'most'),
    ('Latvia', 2, 'most'),
    ('Latvia', 3, 'some'),
    ('Latvia', 5, 'all'),
    ('Latvia', 8, 'some'),
    ('Lebanon', 2, 'most'),
    ('Lebanon', 3, 'some'),
    ('Lebanon', 5, 'all'),
    ('Lebanon', 8, 'some'),
    ('Lebanon', 9, 'most'),
    ('Aruba', 2, 'most'),
    ('Aruba', 3, 'some'),
    ('Aruba', 5, 'all'),
    ('Aruba', 8, 'some'),
    ('Aruba', 9, 'most'),
    ('Lesotho', 2, 'most'),
    ('Lesotho', 3, 'some'),
    ('Lesotho', 5, 'all'),
    ('Lesotho', 8, 'some'),
    ('Lesotho', 9, 'most'),
    ('Liberia', 10, 'all'),
    ('Liberia', 2, 'most'),
    ('Liberia', 3, 'some'),
    ('Liberia', 4, 'most'),
    ('Liberia', 5, 'all'),
    ('Liberia', 8, 'some'),
    ('Liberia', 9, 'most'),
    ('Libya', 2, 'most'),
    ('Libya', 3, 'some'),
    ('Libya', 5, 'all'),
    ('Libya', 8, 'some'),
    ('Libya', 9, 'most'),
    ('Liechtenstein', 2, 'some'),
    ('Liechtenstein', 3, 'some'),
    ('Liechtenstein', 5, 'all'),
    ('Liechtenstein', 8, 'some'),
    ('Lithuania', 2, 'most'),
    ('Lithuania', 3, 'some'),
    ('Lithuania', 5, 'all'),
    ('Lithuania', 8, 'some'),
    ('Luxembourg', 2, 'some'),
    ('Luxembourg', 3, 'some'),
    ('Luxembourg', 5, 'all'),
    ('Luxembourg', 8, 'some'),
    ('Macau SAR', 2, 'most'),
    ('Macau SAR', 3, 'some'),
    ('Macau SAR', 5, 'all'),
    ('Macau SAR', 8, 'some'),
    ('Macau SAR', 9, 'most'),
    ('Madagascar', 2, 'most'),
    ('Madagascar', 3, 'some'),
    ('Madagascar', 4, 'some'),
    ('Madagascar', 5, 'all'),
    ('Madagascar', 8, 'some'),
    ('Madagascar', 9, 'most'),
    ('Madeira Islands', 2, 'some'),
    ('Madeira Islands', 3, 'some'),
    ('Madeira Islands', 5, 'all'),
    ('Madeira Islands', 8, 'some'),
    ('Malawi', 1, 'some'),
    ('Malawi', 2, 'most'),
    ('Malawi', 3, 'some'),
    ('Malawi', 4, 'most'),
    ('Malawi', 5, 'all'),
    ('Malawi', 8, 'some'),
    ('Malawi', 9, 'most'),
    ('Australia', 2, 'some'),
    ('Australia', 3, 'some'),
    ('Australia', 5, 'all'),
    ('Australia', 8, 'some'),
    ('Malaysia', 1, 'some'),
    ('Malaysia', 2, 'most'),
    ('Malaysia', 3, 'some'),
    ('Malaysia', 4, 'some'),
    ('Malaysia', 5, 'all'),
    ('Malaysia', 8, 'some'),
    ('Malaysia', 9, 'most'),
    ('Maldives', 2, 'most'),
    ('Maldives', 3, 'some'),
    ('Maldives', 5, 'all'),
    ('Maldives', 9, 'most'),
    ('Mali', 10, 'all'),
    ('Mali', 2, 'most'),
    ('Mali', 3, 'some'),
    ('Mali', 4, 'most'),
    ('Mali', 5, 'all'),
    ('Mali', 8, 'some'),
    ('Mali', 9, 'most'),
    ('Malta', 2, 'some'),
    ('Malta', 3, 'some'),
    ('Malta', 5, 'all'),
    ('Malta', 8, 'some'),
    ('Marshall Islands', 2, 'most'),
    ('Marshall Islands', 3, 'some'),
    ('Marshall Islands', 5, 'all'),
    ('Marshall Islands', 9, 'most'),
    ('Martinique', 2, 'most'),
    ('Martinique', 3, 'some'),
    ('Martinique', 5, 'all'),
    ('Martinique', 8, 'some'),
    ('Martinique', 9, 'most'),
    ('Mauritania', 2, 'most'),
    ('Mauritania', 3, 'some'),
    ('Mauritania', 4, 'most'),
    ('Mauritania', 5, 'all'),
    ('Mauritania', 8, 'some'),
    ('Mauritania', 9, 'most'),
    ('Mauritius', 2, 'most'),
    ('Mauritius', 3, 'some'),
    ('Mauritius', 5, 'all'),
    ('Mauritius', 8, 'some'),
    ('Mauritius', 9, 'most'),
    ('Mayotte', 2, 'most'),
    ('Mayotte', 3, 'some'),
    ('Mayotte', 4, 'some'),
    ('Mayotte', 5, 'all'),
    ('Mayotte', 8, 'some'),
    ('Mayotte', 9, 'most'),
    ('Mexico', 2, 'most'),
    ('Mexico', 3, 'some'),
    ('Mexico', 4, 'some'),
    ('Mexico', 5, 'all'),
    ('Mexico', 8, 'some'),
    ('Mexico', 9, 'most'),
    ('Austria', 2, 'some'),
    ('Austria', 3, 'some'),
    ('Austria', 5, 'all'),
    ('Austria', 8, 'some'),
    ('Micronesia (Federated States of)', 2, 'most'),
    ('Micronesia (Federated States of)', 3, 'some'),
    ('Micronesia (Federated States of)', 5, 'all'),
    ('Micronesia (Federated States of)', 9, 'most'),
    ('Moldova', 2, 'most'),
    ('Moldova', 3, 'some'),
    ('Moldova', 5, 'all'),
    ('Moldova', 8, 'some'),
    ('Monaco', 2, 'some'),
    ('Monaco', 3, 'some'),
    ('Monaco', 5, 'all'),
    ('Monaco', 8, 'some'),
    ('Mongolia', 2, 'most'),
    ('Mongolia', 3, 'some'),
    ('Mongolia', 5, 'all'),
    ('Mongolia', 8, 'some'),
    ('Mongolia', 9, 'most'),
    ('Montenegro', 2, 'most'),
    ('Montenegro', 3, 'some'),
    ('Montenegro', 5, 'all'),
    ('Montenegro', 8, 'some'),
    ('Montserrat', 2, 'most'),
    ('Montserrat', 3, 'some'),
    ('Montserrat', 5, 'all'),
    ('Montserrat', 8, 'some'),
    ('Montserrat', 9, 'most'),
    ('Morocco', 2, 'most'),
    ('Morocco', 3, 'some'),
    ('Morocco', 5, 'all'),
    ('Morocco', 8, 'some'),
    ('Morocco', 9, 'most'),
    ('Mozambique', 1, 'some'),
    ('Mozambique', 2, 'most'),
    ('Mozambique', 3, 'some'),
    ('Mozambique', 4, 'most'),
    ('Mozambique', 5, 'all'),
    ('Mozambique', 8, 'some'),
    ('Mozambique', 9, 'most'),
    ('Myanmar (Burma)', 1, 'some'),
    ('Myanmar (Burma)', 2, 'most'),
    ('Myanmar (Burma)', 3, 'some'),
    ('Myanmar (Burma)', 4, 'some'),
    ('Myanmar (Burma)', 5, 'all'),
    ('Myanmar (Burma)', 7, 'all'),
    ('Myanmar (Burma)', 8, 'some'),
    ('Myanmar (Burma)', 9, 'most'),
    ('Namibia', 2, 'most'),
    ('Namibia', 3, 'some'),
    ('Namibia', 4, 'some'),
    ('Namibia', 5, 'all'),
    ('Namibia', 8, 'some'),
    ('Namibia', 9, 'most'),
    ('Azerbaijan', 2, 'most'),
    ('Azerbaijan', 3, 'some'),
    ('Azerbaijan', 4, 'some'),
    ('Azerbaijan', 5, 'all'),
    ('Azerbaijan', 8, 'some'),
    ('Nauru', 2, 'most'),
    ('Nauru', 3, 'some'),
    ('Nauru', 5, 'all'),
    ('Nauru', 9, 'most'),
    ('Nepal', 2, 'most'),
    ('Nepal', 3, 'some'),
    ('Nepal', 4, 'some'),
    ('Nepal', 5, 'all'),
    ('Nepal', 8, 'some'),
    ('Nepal', 9, 'most'),
    ('Netherlands', 2, 'some'),
    ('Netherlands', 3, 'some'),
    ('Netherlands', 5, 'all'),
    ('Netherlands', 8, 'some'),
    ('New Caledonia', 2, 'most'),
    ('New Caledonia', 3, 'some'),
    ('New Caledonia', 5, 'all'),
    ('New Caledonia', 9, 'most'),
    ('New Zealand (Aotearoa)', 2, 'some'),
    ('New Zealand (Aotearoa)', 3, 'some'),
    ('New Zealand (Aotearoa)', 5, 'all'),
    ('Nicaragua', 2, 'most'),
    ('Nicaragua', 3, 'some'),
    ('Nicaragua', 4, 'some'),
    ('Nicaragua', 5, 'all'),
    ('Nicaragua', 8, 'some'),
    ('Nicaragua', 9, 'most'),
    ('Niger', 1, 'some'),
    ('Niger', 10, 'all'),
    ('Niger', 2, 'most'),
    ('Niger', 3, 'some'),
    ('Niger', 4, 'most'),
    ('Niger', 5, 'all'),
    ('Niger', 8, 'some'),
    ('Niger', 9, 'most'),
    ('Nigeria', 1, 'some'),
    ('Nigeria', 10, 'all'),
    ('Nigeria', 2, 'most'),
    ('Nigeria', 3, 'some'),
    ('Nigeria', 4, 'most'),
    ('Nigeria', 5, 'all'),
    ('Nigeria', 7, 'all'),
    ('Nigeria', 8, 'some'),
    ('Nigeria', 9, 'most'),
    ('Niue', 2, 'most'),
    ('Niue', 3, 'some'),
    ('Niue', 9, 'most'),
    ('Norfolk Island', 2, 'most'),
    ('Norfolk Island', 3, 'some'),
    ('Norfolk Island', 5, 'all'),
    ('Norfolk Island', 9, 'most'),
    ('Azores', 2, 'some'),
    ('Azores', 3, 'some'),
    ('Azores', 5, 'all'),
    ('Azores', 8, 'some'),
    ('North Korea', 2, 'most'),
    ('North Korea', 3, 'some'),
    ('North Korea', 4, 'some'),
    ('North Korea', 5, 'all'),
    ('North Korea', 8, 'some'),
    ('North Korea', 9, 'most'),
    ('North Macedonia', 2, 'most'),
    ('North Macedonia', 3, 'some'),
    ('North Macedonia', 5, 'all'),
    ('North Macedonia', 8, 'some'),
    ('Northern Mariana Islands', 2, 'most'),
    ('Northern Mariana Islands', 3, 'some'),
    ('Northern Mariana Islands', 9, 'most'),
    ('Norway', 2, 'some'),
    ('Norway', 3, 'some'),
    ('Norway', 5, 'all'),
    ('Norway', 8, 'some'),
    ('Oman', 2, 'most'),
    ('Oman', 3, 'some'),
    ('Oman', 4, 'some'),
    ('Oman', 5, 'all'),
    ('Oman', 8, 'some'),
    ('Oman', 9, 'most'),
    ('Pakistan', 2, 'most'),
    ('Pakistan', 3, 'some'),
    ('Pakistan', 4, 'some'),
    ('Pakistan', 5, 'all'),
    ('Pakistan', 7, 'all'),
    ('Pakistan', 8, 'some'),
    ('Pakistan', 9, 'most'),
    ('Palau', 2, 'most'),
    ('Palau', 3, 'some'),
    ('Palau', 5, 'all'),
    ('Palau', 9, 'most'),
    ('Panama', 2, 'most'),
    ('Panama', 3, 'some'),
    ('Panama', 4, 'some'),
    ('Panama', 5, 'all'),
    ('Panama', 8, 'some'),
    ('Panama', 9, 'most'),
    ('Papua New Guinea', 2, 'most'),
    ('Papua New Guinea', 3, 'some'),
    ('Papua New Guinea', 4, 'some'),
    ('Papua New Guinea', 5, 'all'),
    ('Papua New Guinea', 7, 'all'),
    ('Papua New Guinea', 8, 'some'),
    ('Papua New Guinea', 9, 'most'),
    ('Paraguay', 2, 'most'),
    ('Paraguay', 3, 'some'),
    ('Paraguay', 4, 'some'),
    ('Paraguay', 5, 'all'),
    ('Paraguay', 8, 'some'),
    ('Paraguay', 9, 'most'),
    ('Bahamas (The)', 2, 'most'),
    ('Bahamas (The)', 3, 'some'),
    ('Bahamas (The)', 5, 'all'),
    ('Bahamas (The)', 8, 'some'),
    ('Bahamas (The)', 9, 'most'),
    ('Peru', 2, 'most'),
    ('Peru', 3, 'some'),
    ('Peru', 4, 'some'),
    ('Peru', 5, 'all'),
    ('Peru', 8, 'some'),
    ('Peru', 9, 'most'),
    ('Philippines', 1, 'some'),
    ('Philippines', 2, 'most'),
    ('Philippines', 3, 'some'),
    ('Philippines', 4, 'some'),
    ('Philippines', 5, 'all'),
    ('Philippines', 7, 'all'),
    ('Philippines', 8, 'some'),
    ('Philippines', 9, 'most'),
    ('Pitcairn Islands', 2, 'most'),
    ('Pitcairn Islands', 3, 'some'),
    ('Pitcairn Islands', 5, 'all'),
    ('Pitcairn Islands', 9, 'most'),
    ('Poland', 2, 'most'),
    ('Poland', 3, 'some'),
    ('Poland', 5, 'all'),
    ('Poland', 8, 'some'),
    ('Portugal', 2, 'some'),
    ('Portugal', 3, 'some'),
    ('Portugal', 5, 'all'),
    ('Portugal', 8, 'some'),
    ('Puerto Rico', 2, 'most'),
    ('Puerto Rico', 3, 'some'),
    ('Puerto Rico', 8, 'some'),
    ('Puerto Rico', 9, 'most'),
    ('Qatar', 2, 'most'),
    ('Qatar', 3, 'some'),
    ('Qatar', 5, 'all'),
    ('Qatar', 8, 'some'),
    ('Qatar', 9, 'most'),
    ('Réunion', 2, 'most'),
    ('Réunion', 3, 'some'),
    ('Réunion', 5, 'all'),
    ('Réunion', 8, 'some'),
    ('Réunion', 9, 'most'),
    ('Romania', 2, 'most'),
    ('Romania', 3, 'some'),
    ('Romania', 5, 'all'),
    ('Romania', 8, 'some'),
    ('Russia', 2, 'most'),
    ('Russia', 3, 'some'),
    ('Russia', 5, 'all'),
    ('Russia', 8, 'some'),
    ('Bahrain', 2, 'most'),
    ('Bahrain', 3, 'some'),
    ('Bahrain', 5, 'all'),
    ('Bahrain', 8, 'some'),
    ('Bahrain', 9, 'most'),
    ('Rwanda', 2, 'most'),
    ('Rwanda', 3, 'some'),
    ('Rwanda', 4, 'most'),
    ('Rwanda', 5, 'all'),
    ('Rwanda', 8, 'some'),
    ('Rwanda', 9, 'most'),
    ('Saba', 2, 'most'),
    ('Saba', 3, 'some'),
    ('Saba', 5, 'all'),
    ('Saba', 8, 'some'),
    ('Saba', 9, 'most'),
    ('Saint Barthélemy', 2, 'most'),
    ('Saint Barthélemy', 3, 'some'),
    ('Saint Barthélemy', 5, 'all'),
    ('Saint Barthélemy', 8, 'some'),
    ('Saint Barthélemy', 9, 'most'),
    ('Saint Helena', 2, 'most'),
    ('Saint Helena', 3, 'some'),
    ('Saint Helena', 5, 'all'),
    ('Saint Helena', 8, 'some'),
    ('Saint Helena', 9, 'most'),
    ('Saint Kitts and Nevis', 2, 'most'),
    ('Saint Kitts and Nevis', 3, 'some'),
    ('Saint Kitts and Nevis', 5, 'all'),
    ('Saint Kitts and Nevis', 8, 'some'),
    ('Saint Kitts and Nevis', 9, 'most'),
    ('Saint Lucia', 2, 'most'),
    ('Saint Lucia', 3, 'some'),
    ('Saint Lucia', 5, 'all'),
    ('Saint Lucia', 8, 'some'),
    ('Saint Lucia', 9, 'most'),
    ('Saint Martin', 2, 'most'),
    ('Saint Martin', 3, 'some'),
    ('Saint Martin', 5, 'all'),
    ('Saint Martin', 8, 'some'),
    ('Saint Martin', 9, 'most'),
    ('Saint Pierre and Miquelon', 2, 'some'),
    ('Saint Pierre and Miquelon', 3, 'some'),
    ('Saint Pierre and Miquelon', 5, 'all'),
    ('Saint Pierre and Miquelon', 8, 'some'),
    ('Saint Vincent and the Grenadines', 2, 'most'),
    ('Saint Vincent and the Grenadines', 3, 'some'),
    ('Saint Vincent and the Grenadines', 5, 'all'),
    ('Saint Vincent and the Grenadines', 8, 'some'),
    ('Saint Vincent and the Grenadines', 9, 'most'),
    ('Samoa', 2, 'most'),
    ('Samoa', 3, 'some'),
    ('Samoa', 5, 'all'),
    ('Samoa', 9, 'most'),
    ('Bangladesh', 1, 'some'),
    ('Bangladesh', 2, 'most'),
    ('Bangladesh', 3, 'some'),
    ('Bangladesh', 4, 'some'),
    ('Bangladesh', 5, 'all'),
    ('Bangladesh', 8, 'some'),
    ('Bangladesh', 9, 'most'),
    ('San Marino', 2, 'some'),
    ('San Marino', 3, 'some'),
    ('San Marino', 5, 'all'),
    ('San Marino', 8, 'some'),
    ('São Tomé and Príncipe', 2, 'most'),
    ('São Tomé and Príncipe', 3, 'some'),
    ('São Tomé and Príncipe', 4, 'most'),
    ('São Tomé and Príncipe', 5, 'all'),
    ('São Tomé and Príncipe', 8, 'some'),
    ('São Tomé and Príncipe', 9, 'most'),
    ('Saudi Arabia', 2, 'most'),
    ('Saudi Arabia', 3, 'some'),
    ('Saudi Arabia', 4, 'some'),
    ('Saudi Arabia', 5, 'all'),
    ('Saudi Arabia', 8, 'some'),
    ('Saudi Arabia', 9, 'most'),
    ('Senegal', 10, 'most'),
    ('Senegal', 2, 'most'),
    ('Senegal', 3, 'some'),
    ('Senegal', 4, 'most'),
    ('Senegal', 5, 'all'),
    ('Senegal', 8, 'some'),
    ('Senegal', 9, 'most'),
    ('Serbia', 2, 'most'),
    ('Serbia', 3, 'some'),
    ('Serbia', 5, 'all'),
    ('Serbia', 8, 'some'),
    ('Seychelles', 2, 'most'),
    ('Seychelles', 3, 'some'),
    ('Seychelles', 5, 'all'),
    ('Seychelles', 8, 'some'),
    ('Seychelles', 9, 'most'),
    ('Sierra Leone', 10, 'all'),
    ('Sierra Leone', 2, 'most'),
    ('Sierra Leone', 3, 'some'),
    ('Sierra Leone', 4, 'most'),
    ('Sierra Leone', 5, 'all'),
    ('Sierra Leone', 8, 'some'),
    ('Sierra Leone', 9, 'most'),
    ('Singapore', 2, 'most'),
    ('Singapore', 3, 'some'),
    ('Singapore', 5, 'all'),
    ('Singapore', 8, 'some'),
    ('Singapore', 9, 'most'),
    ('Sint Eustatius', 2, 'most'),
    ('Sint Eustatius', 3, 'some'),
    ('Sint Eustatius', 5, 'all'),
    ('Sint Eustatius', 8, 'some'),
    ('Sint Eustatius', 9, 'most'),
    ('Sint Maarten', 2, 'most'),
    ('Sint Maarten', 3, 'some'),
    ('Sint Maarten', 5, 'all'),
    ('Sint Maarten', 8, 'some'),
    ('Sint Maarten', 9, 'most'),
    ('Albania', 2, 'most'),
    ('Albania', 3, 'some'),
    ('Albania', 5, 'all'),
    ('Albania', 8, 'some'),
    ('Barbados', 2, 'most'),
    ('Barbados', 3, 'some'),
    ('Barbados', 5, 'all'),
    ('Barbados', 8, 'some'),
    ('Barbados', 9, 'most'),
    ('Slovakia', 2, 'most'),
    ('Slovakia', 3, 'some'),
    ('Slovakia', 5, 'all'),
    ('Slovakia', 8, 'some'),
    ('Slovenia', 2, 'most'),
    ('Slovenia', 3, 'some'),
    ('Slovenia', 5, 'all'),
    ('Slovenia', 8, 'some'),
    ('Solomon Islands', 2, 'most'),
    ('Solomon Islands', 3, 'some'),
    ('Solomon Islands', 4, 'most'),
    ('Solomon Islands', 5, 'all'),
    ('Solomon Islands', 9, 'most'),
    ('Somalia', 1, 'some'),
    ('Somalia', 2, 'most'),
    ('Somalia', 3, 'some'),
    ('Somalia', 4, 'most'),
    ('Somalia', 5, 'all'),
    ('Somalia', 7, 'all'),
    ('Somalia', 8, 'some'),
    ('Somalia', 9, 'most'),
    ('South Africa', 2, 'most'),
    ('South Africa', 3, 'some'),
    ('South Africa', 4, 'some'),
    ('South Africa', 5, 'all'),
    ('South Africa', 8, 'some'),
    ('South Africa', 9, 'most'),
    ('South Georgia and the South Sandwich Islands', 2, 'most'),
    ('South Georgia and the South Sandwich Islands', 3, 'some'),
    ('South Georgia and the South Sandwich Islands', 5, 'all'),
    ('South Georgia and the South Sandwich Islands', 9, 'most'),
    ('South Korea', 2, 'most'),
    ('South Korea', 3, 'some'),
    ('South Korea', 4, 'some'),
    ('South Korea', 5, 'all'),
    ('South Korea', 8, 'some'),
    ('South Korea', 9, 'most'),
    ('South Sudan', 1, 'some'),
    ('South Sudan', 10, 'most'),
    ('South Sudan', 2, 'most'),
    ('South Sudan', 3, 'some'),
    ('South Sudan', 4, 'most'),
    ('South Sudan', 5, 'all'),
    ('South Sudan', 8, 'some'),
    ('South Sudan', 9, 'most'),
    ('Spain', 2, 'some'),
    ('Spain', 3, 'some'),
    ('Spain', 5, 'all'),
    ('Spain', 8, 'some'),
    ('Sri lanka', 2, 'most'),
    ('Sri Lanka', 3, 'some'),
    ('Sri Lanka', 5, 'all'),
    ('Sri Lanka', 8, 'some'),
    ('Sri Lanka', 9, 'most'),
    ('Belarus', 2, 'most'),
    ('Belarus', 3, 'some'),
    ('Belarus', 5, 'all'),
    ('Belarus', 8, 'some'),
    ('Sudan', 1, 'some'),
    ('Sudan', 2, 'most'),
    ('Sudan', 3, 'some'),
    ('Sudan', 4, 'most'),
    ('Sudan', 5, 'all'),
    ('Sudan', 8, 'some'),
    ('Sudan', 9, 'most'),
    ('Suriname', 10, 'most'),
    ('Suriname', 2, 'most'),
    ('Suriname', 3, 'some'),
    ('Suriname', 4, 'some'),
    ('Suriname', 5, 'all'),
    ('Suriname', 8, 'some'),
    ('Suriname', 9, 'most'),
    ('Sweden', 2, 'some'),
    ('Sweden', 3, 'some'),
    ('Sweden', 5, 'all'),
    ('Sweden', 8, 'some'),
    ('Switzerland', 2, 'some'),
    ('Switzerland', 3, 'some'),
    ('Switzerland', 5, 'all'),
    ('Switzerland', 8, 'some'),
    ('Syria', 2, 'most'),
    ('Syria', 3, 'some'),
    ('Syria', 5, 'all'),
    ('Syria', 8, 'some'),
    ('Syria', 9, 'most'),
    ('Taiwan', 2, 'most'),
    ('Taiwan', 3, 'some'),
    ('Taiwan', 5, 'all'),
    ('Taiwan', 8, 'some'),
    ('Tajikistan', 2, 'most'),
    ('Tajikistan', 3, 'some'),
    ('Tajikistan', 4, 'some'),
    ('Tajikistan', 5, 'all'),
    ('Tajikistan', 8, 'some'),
    ('Tajikistan', 9, 'most'),
    ('Tanzania', 1, 'some'),
    ('Tanzania', 2, 'most'),
    ('Tanzania', 3, 'some'),
    ('Tanzania', 4, 'some'),
    ('Tanzania', 5, 'all'),
    ('Tanzania', 8, 'some'),
    ('Tanzania', 9, 'most'),
    ('Thailand', 1, 'some'),
    ('Thailand', 2, 'most'),
    ('Thailand', 3, 'some'),
    ('Thailand', 4, 'some'),
    ('Thailand', 5, 'all'),
    ('Thailand', 8, 'some'),
    ('Thailand', 9, 'most'),
    ('Timor-Leste (East Timor)', 2, 'most'),
    ('Togo', 3, 'some'),
    ('Togo', 4, 'most'),
    ('Togo', 5, 'all'),
    ('Togo', 8, 'some'),
    ('Togo', 9, 'most'),
    ('Belgium', 2, 'some'),
    ('Belgium', 3, 'some'),
    ('Belgium', 5, 'all'),
    ('Belgium', 8, 'some'),
    ('Togo', 10, 'all'),
    ('Togo', 2, 'most'),
    ('Togo', 3, 'some'),
    ('Togo', 4, 'most'),
    ('Togo', 5, 'all'),
    ('Togo', 8, 'some'),
    ('Togo', 9, 'most'),
    ('Tokelau', 2, 'most'),
    ('Tokelau', 3, 'some'),
    ('Tokelau', 5, 'all'),
    ('Tokelau', 9, 'most'),
    ('Tonga', 2, 'most'),
    ('Tonga', 3, 'some'),
    ('Tonga', 5, 'all'),
    ('Tonga', 9, 'most'),
    ('Trinidad and Tobago', 2, 'most'),
    ('Trinidad and Tobago', 3, 'some'),
    ('Trinidad and Tobago', 5, 'all'),
    ('Trinidad and Tobago', 8, 'some'),
    ('Trinidad and Tobago', 9, 'most'),
    ('Tunisia', 2, 'most'),
    ('Tunisia', 3, 'some'),
    ('Tunisia', 5, 'all'),
    ('Tunisia', 8, 'some'),
    ('Tunisia', 9, 'most'),
    ('Turkey', 2, 'most'),
    ('Turkey', 3, 'some'),
    ('Turkey', 5, 'all'),
    ('Turkey', 8, 'some'),
    ('Turkey', 9, 'most'),
    ('Turkmenistan', 2, 'most'),
    ('Turkmenistan', 3, 'some'),
    ('Turkmenistan', 5, 'all'),
    ('Turkmenistan', 8, 'some'),
    ('Turkmenistan', 9, 'most'),
    ('Turks and Caicos Islands', 2, 'most'),
    ('Turks and Caicos Islands', 3, 'some'),
    ('Turks and Caicos Islands', 5, 'all'),
    ('Turks and Caicos Islands', 8, 'some'),
    ('Turks and Caicos Islands', 9, 'most'),
    ('Tuvalu', 2, 'most'),
    ('Tuvalu', 3, 'some'),
    ('Tuvalu', 5, 'all'),
    ('Tuvalu', 9, 'most'),
    ('Uganda', 1, 'some'),
    ('Uganda', 10, 'all'),
    ('Uganda', 2, 'most'),
    ('Uganda', 3, 'some'),
    ('Uganda', 4, 'most'),
    ('Uganda', 5, 'all'),
    ('Uganda', 8, 'some'),
    ('Uganda', 9, 'most'),
    ('Belize', 2, 'most'),
    ('Belize', 3, 'some'),
    ('Belize', 4, 'some'),
    ('Belize', 5, 'all'),
    ('Belize', 8, 'some'),
    ('Belize', 9, 'most'),
    ('Ukraine', 2, 'most'),
    ('Ukraine', 3, 'some'),
    ('Ukraine', 5, 'all'),
    ('Ukraine', 8, 'some'),
    ('United Arab Emirates', 2, 'most'),
    ('United Arab Emirates', 3, 'some'),
    ('United Arab Emirates', 5, 'all'),
    ('United Arab Emirates', 8, 'some'),
    ('United Arab Emirates', 9, 'most'),
    ('United Kingdom', 2, 'some'),
    ('United Kingdom', 3, 'some'),
    ('United Kingdom', 5, 'all'),
    ('United Kingdom', 8, 'some'),
    ('United States', 3, 'some'),
    ('United States', 8, 'some'),
    ('Uruguay', 2, 'most'),
    ('Uruguay', 3, 'some'),
    ('Uruguay', 5, 'all'),
    ('Uruguay', 8, 'some'),
    ('Uruguay', 9, 'most'),
    ('Uzbekistan', 2, 'most'),
    ('Uzbekistan', 3, 'some'),
    ('Uzbekistan', 5, 'all'),
    ('Uzbekistan', 8, 'some'),
    ('Uzbekistan', 9, 'most'),
    ('Vanuatu', 2, 'most'),
    ('Vanuatu', 3, 'some'),
    ('Vanuatu', 4, 'most'),
    ('Vanuatu', 5, 'all'),
    ('Vanuatu', 9, 'most'),
    ('Venezuela', 2, 'most'),
    ('Venezuela', 3, 'some'),
    ('Venezuela', 4, 'some'),
    ('Venezuela', 5, 'all'),
    ('Venezuela', 8, 'some'),
    ('Venezuela', 9, 'most'),
    ('Vietnam', 2, 'most'),
    ('Vietnam', 3, 'some'),
    ('Vietnam', 4, 'some'),
    ('Vietnam', 5, 'all'),
    ('Vietnam', 8, 'some'),
    ('Vietnam', 9, 'most'),
    ('Benin', 1, 'some'),
    ('Benin', 10, 'all'),
    ('Benin', 2, 'most'),
    ('Benin', 3, 'some'),
    ('Benin', 4, 'most'),
    ('Benin', 5, 'all'),
    ('Benin', 7, 'all'),
    ('Benin', 8, 'some'),
    ('Benin', 9, 'most'),
    ('Virgin Islands (British)', 2, 'most'),
    ('Virgin Islands (British)', 3, 'some'),
    ('Virgin Islands (British)', 5, 'all'),
    ('Virgin Islands (British)', 8, 'some'),
    ('Virgin Islands (British)', 9, 'most'),
    ('Virgin Islands (US)', 2, 'most'),
    ('Virgin Islands (US)', 3, 'some'),
    ('Virgin Islands (US)', 8, 'some'),
    ('Virgin Islands (US)', 9, 'most'),
    ('Wake Island', 2, 'most'),
    ('Wake Island', 3, 'some'),
    ('Wake Island', 5, 'all'),
    ('Wake Island', 9, 'most'),
    ('Western Sahara', 2, 'most'),
    ('Western Sahara', 3, 'some'),
    ('Western Sahara', 4, 'some'),
    ('Western Sahara', 5, 'all'),
    ('Western Sahara', 8, 'some'),
    ('Western Sahara', 9, 'most'),
    ('Yemen', 1, 'some'),
    ('Yemen', 2, 'most'),
    ('Yemen', 3, 'some'),
    ('Yemen', 4, 'some'),
    ('Yemen', 5, 'all'),
    ('Yemen', 8, 'some'),
    ('Yemen', 9, 'most'),
    ('Zambia', 1, 'some'),
    ('Zambia', 2, 'most'),
    ('Zambia', 3, 'some'),
    ('Zambia', 4, 'most'),
    ('Zambia', 5, 'all'),
    ('Zambia', 7, 'all'),
    ('Zambia', 8, 'some'),
    ('Zambia', 9, 'most'),
    ('Zimbabwe', 1, 'some'),
    ('Zimbabwe', 2, 'most'),
    ('Zimbabwe', 3, 'some'),
    ('Zimbabwe', 4, 'most'),
    ('Zimbabwe', 5, 'all'),
    ('Zimbabwe', 8, 'some'),
    ('Zimbabwe', 9, 'most'),
    ('Bermuda', 2, 'most'),
    ('Bermuda', 3, 'some'),
    ('Bermuda', 5, 'all'),
    ('Bermuda', 8, 'some'),
    ('Bermuda', 9, 'most'),
    ('Bhutan', 2, 'most'),
    ('Bhutan', 3, 'some'),
    ('Bhutan', 4, 'some'),
    ('Bhutan', 5, 'all'),
    ('Bhutan', 8, 'some'),
    ('Bhutan', 9, 'most'),
    ('Bolivia', 2, 'most'),
    ('Bolivia', 3, 'some'),
    ('Bolivia', 4, 'some'),
    ('Bolivia', 5, 'all'),
    ('Bolivia', 8, 'some'),
    ('Bolivia', 9, 'most'),
    ('Bonaire', 2, 'most'),
    ('Bonaire', 3, 'some'),
    ('Bonaire', 5, 'all'),
    ('Bonaire', 8, 'some'),
    ('Bonaire', 9, 'most'),
    ('Bosnia and Herzegovina', 2, 'most'),
    ('Bosnia and Herzegovina', 3, 'some'),
    ('Bosnia and Herzegovina', 5, 'all'),
    ('Bosnia and Herzegovina', 8, 'some'),
    ('Algeria', 1, 'some'),
    ('Algeria', 2, 'most'),
    ('Algeria', 3, 'some'),
    ('Algeria', 4, 'some'),
    ('Algeria', 5, 'all'),
    ('Algeria', 8, 'some'),
    ('Algeria', 9, 'most'),
    ('Botswana', 2, 'most'),
    ('Botswana', 3, 'some'),
    ('Botswana', 4, 'some'),
    ('Botswana', 5, 'all'),
    ('Botswana', 8, 'some'),
    ('Botswana', 9, 'most'),
    ('Brazil', 10, 'most'),
    ('Brazil', 2, 'most'),
    ('Brazil', 3, 'some'),
    ('Brazil', 4, 'some'),
    ('Brazil', 5, 'all'),
    ('Brazil', 8, 'some'),
    ('Brazil', 9, 'most'),
    ('British Indian Ocean Territory', 2, 'most'),
    ('British Indian Ocean Territory', 3, 'some'),
    ('British Indian Ocean Territory', 5, 'all'),
    ('British Indian Ocean Territory', 9, 'most'),
    ('Brunei', 2, 'some'),
    ('Brunei', 3, 'some'),
    ('Brunei', 5, 'all'),
    ('Brunei', 8, 'some'),
    ('Brunei', 9, 'most'),
    ('Bulgaria', 2, 'most'),
    ('Bulgaria', 3, 'some'),
    ('Bulgaria', 5, 'all'),
    ('Bulgaria', 8, 'some'),
    ('Burkina Faso', 10, 'most'),
    ('Burkina Faso', 2, 'most'),
    ('Burkina Faso', 3, 'some'),
    ('Burkina Faso', 4, 'most'),
    ('Burkina Faso', 5, 'all'),
    ('Burkina Faso', 8, 'some'),
    ('Burkina Faso', 9, 'most'),
    ('Burundi', 1, 'some'),
    ('Burundi', 10, 'all'),
    ('Burundi', 2, 'most'),
    ('Burundi', 3, 'some'),
    ('Burundi', 4, 'most'),
    ('Burundi', 5, 'all'),
    ('Burundi', 8, 'some'),
    ('Burundi', 9, 'most'),
    ('Cambodia', 2, 'most'),
    ('Cambodia', 3, 'some'),
    ('Cambodia', 4, 'some'),
    ('Cambodia', 5, 'all'),
    ('Cambodia', 8, 'some'),
    ('Cambodia', 9, 'most'),
    ('Cameroon', 1, 'some'),
    ('Cameroon', 10, 'all'),
    ('Cameroon', 2, 'most'),
    ('Cameroon', 3, 'some'),
    ('Cameroon', 4, 'most'),
    ('Cameroon', 5, 'all'),
    ('Cameroon', 7, 'all'),
    ('Cameroon', 8, 'some'),
    ('Cameroon', 9, 'most'),
    ('Canada', 2, 'some'),
    ('Canada', 3, 'some'),
    ('Canada', 5, 'all'),
    ('Canada', 8, 'some'),
    ('American Samoa', 2, 'most'),
    ('American Samoa', 3, 'some'),
    ('American Samoa', 9, 'most'),
    ('Canary Islands', 2, 'some'),
    ('Canary Islands', 3, 'some'),
    ('Canary Islands', 5, 'all'),
    ('Canary Islands', 8, 'some'),
    ('Cape Verde', 2, 'most'),
    ('Cape Verde', 3, 'some'),
    ('Cape Verde', 4, 'some'),
    ('Cape Verde', 5, 'all'),
    ('Cape Verde', 8, 'some'),
    ('Cape Verde', 9, 'most'),
    ('Cayman Islands', 2, 'most'),
    ('Cayman Islands', 3, 'some'),
    ('Cayman Islands', 5, 'all'),
    ('Cayman Islands', 8, 'some'),
    ('Cayman Islands', 9, 'most'),
    ('Central African Republic', 1, 'some'),
    ('Central African Republic', 10, 'all'),
    ('Central African Republic', 2, 'most'),
    ('Central African Republic', 3, 'some'),
    ('Central African Republic', 4, 'most'),
    ('Central African Republic', 5, 'all'),
    ('Central African Republic', 7, 'all'),
    ('Central African Republic', 8, 'some'),
    ('Central African Republic', 9, 'most'),
    ('Chad', 1, 'some'),
    ('Chad', 2, 'most'),
    ('Chad', 3, 'some'),
    ('Chad', 4, 'most'),
    ('Chad', 5, 'all'),
    ('Chad', 7, 'all'),
    ('Chad', 8, 'some'),
    ('Chad', 9, 'most'),
    ('Chile', 2, 'most'),
    ('Chile', 3, 'some'),
    ('Chile', 5, 'all'),
    ('Chile', 8, 'some'),
    ('Chile', 9, 'most'),
    ('China', 2, 'most'),
    ('China', 3, 'some'),
    ('China', 4, 'some'),
    ('China', 5, 'all'),
    ('China', 8, 'some'),
    ('China', 9, 'most'),
    ('Christmas Island (Australia)', 2, 'most'),
    ('Christmas Island (Australia)', 3, 'some'),
    ('Christmas Island (Australia)', 5, 'all'),
    ('Christmas Island (Australia)', 9, 'most'),
    ('Cocos (Keeling) Islands', 2, 'most'),
    ('Cocos (Keeling) Islands', 3, 'some'),
    ('Cocos (Keeling) Islands', 5, 'all'),
    ('Cocos (Keeling) Islands', 9, 'most'),
    ('Colombia', 2, 'most'),
    ('Colombia', 3, 'some'),
    ('Colombia', 4, 'some'),
    ('Colombia', 5, 'all'),
    ('Colombia', 8, 'some'),
    ('Colombia', 9, 'most'),
    ('Andorra', 2, 'some'),
    ('Andorra', 3, 'some'),
    ('Andorra', 5, 'all'),
    ('Andorra', 8, 'some'),
    ("Côte d'Ivoire", 1, 'some'),
    ("Côte d'Ivoire", 10, 'all'),
    ("Côte d'Ivoire", 2, 'most'),
    ("Côte d'Ivoire", 3, 'some'),
    ("Côte d'Ivoire", 4, 'most'),
    ("Côte d'Ivoire", 5, 'all'),
    ("Côte d'Ivoire", 8, 'some'),
    ("Côte d'Ivoire", 9, 'most'),
    ('Comoros', 2, 'most'),
    ('Comoros', 3, 'some'),
    ('Comoros', 4, 'most'),
    ('Comoros', 5, 'all'),
    ('Comoros', 8, 'some'),
    ('Comoros', 9, 'most'),
    ('Congo (Democratic Republic of the)', 1, 'some'),
    ('Congo (Democratic Republic of the)', 10, 'all'),
    ('Congo (Democratic Republic of the)', 2, 'most'),
    ('Congo (Democratic Republic of the)', 3, 'some'),
    ('Congo (Democratic Republic of the)', 4, 'most'),
    ('Congo (Democratic Republic of the)', 5, 'all'),
    ('Congo (Democratic Republic of the)', 7, 'all'),
    ('Congo (Democratic Republic of the)', 8, 'some'),
    ('Congo (Democratic Republic of the)', 9, 'most'),
    ('Congo (Republic of the)', 10, 'all'),
    ('Congo (Republic of the)', 2, 'most'),
    ('Congo (Republic of the)', 3, 'some'),
    ('Congo (Republic of the)', 4, 'most'),
    ('Congo (Republic of the)', 5, 'all'),
    ('Congo (Republic of the)', 8, 'some'),
    ('Congo (Republic of the)', 9, 'most'),
    ('Cook Islands', 2, 'most'),
    ('Cook Islands', 3, 'some'),
    ('Cook Islands', 5, 'all'),
    ('Cook Islands', 9, 'most'),
    ('Costa Rica', 2, 'most'),
    ('Costa Rica', 3, 'some'),
    ('Costa Rica', 4, 'some'),
    ('Costa Rica', 5, 'all'),
    ('Costa Rica', 8, 'some'),
    ('Costa Rica', 9, 'most'),
    ('Croatia', 2, 'most'),
    ('Croatia', 3, 'some'),
    ('Croatia', 5, 'all'),
    ('Croatia', 8, 'some'),
    ('Cuba', 2, 'most'),
    ('Cuba', 3, 'some'),
    ('Cuba', 5, 'all'),
    ('Cuba', 8, 'some'),
    ('Cuba', 9, 'most'),
    ('Curaçao', 2, 'most'),
    ('Curaçao', 3, 'some'),
    ('Curaçao', 5, 'all'),
    ('Curaçao', 8, 'some'),
    ('Curaçao', 9, 'most'),
    ('Cyprus', 2, 'most'),
    ('Cyprus', 3, 'some'),
    ('Cyprus', 5, 'all'),
    ('Cyprus', 8, 'some'),
    ('Angola', 1, 'some'),
    ('Angola', 10, 'all'),
    ('Angola', 2, 'most'),
    ('Angola', 3, 'some'),
    ('Angola', 4, 'most'),
    ('Angola', 5, 'all'),
    ('Angola', 7, 'all'),
    ('Angola', 8, 'some'),
    ('Angola', 9, 'most'),
    ('Czech Republic', 2, 'most'),
    ('Czech Republic', 3, 'some'),
    ('Czech Republic', 5, 'all'),
    ('Czech Republic', 8, 'some'),
    ('Denmark', 2, 'some'),
    ('Denmark', 3, 'some'),
    ('Denmark', 5, 'all'),
    ('Denmark', 8, 'some'),
    ('Djibouti', 2, 'most'),
    ('Djibouti', 3, 'some'),
    ('Djibouti', 4, 'most'),
    ('Djibouti', 5, 'all'),
    ('Djibouti', 8, 'some'),
    ('Djibouti', 9, 'most'),
    ('Dominica', 2, 'most'),
    ('Dominica', 3, 'some'),
    ('Dominica', 5, 'all'),
    ('Dominica', 8, 'some'),
    ('Dominica', 9, 'most'),
    ('Dominican Republic', 1, 'some'),
    ('Dominican Republic', 2, 'most'),
    ('Dominican Republic', 3, 'some'),
    ('Dominican Republic', 4, 'some'),
    ('Dominican Republic', 5, 'all'),
    ('Dominican Republic', 8, 'some'),
    ('Dominican Republic', 9, 'most'),
    ('Easter Island', 2, 'most'),
    ('Easter Island', 3, 'some'),
    ('Easter Island', 5, 'all'),
    ('Easter Island', 9, 'most'),
    ('Ecuador', 2, 'most'),
    ('Ecuador', 3, 'some'),
    ('Ecuador', 4, 'some'),
    ('Ecuador', 5, 'all'),
    ('Ecuador', 8, 'some'),
    ('Ecuador', 9, 'most'),
    ('Egypt', 2, 'most'),
    ('Egypt', 3, 'some'),
    ('Egypt', 5, 'all'),
    ('Egypt', 8, 'some'),
    ('Egypt', 9, 'most'),
    ('El Salvador', 2, 'most'),
    ('El Salvador', 3, 'some'),
    ('El Salvador', 4, 'some'),
    ('El Salvador', 5, 'all'),
    ('El Salvador', 8, 'some'),
    ('El Salvador', 9, 'most'),
    ('Equatorial Guinea', 10, 'most'),
    ('Equatorial Guinea', 2, 'most'),
    ('Equatorial Guinea', 3, 'some'),
    ('Equatorial Guinea', 4, 'most'),
    ('Equatorial Guinea', 5, 'all'),
    ('Equatorial Guinea', 8, 'some'),
    ('Equatorial Guinea', 9, 'most'),
    ('Anguilla', 2, 'most'),
    ('Anguilla', 3, 'some'),
    ('Anguilla', 5, 'all'),
    ('Anguilla', 8, 'some'),
    ('Anguilla', 9, 'most'),
    ('Eritrea', 2, 'most'),
    ('Eritrea', 3, 'some'),
    ('Eritrea', 4, 'some'),
    ('Eritrea', 5, 'all'),
    ('Eritrea', 8, 'some'),
    ('Eritrea', 9, 'most'),
    ('Estonia', 2, 'most'),
    ('Estonia', 3, 'some'),
    ('Estonia', 5, 'all'),
    ('Estonia', 8, 'some'),
    ('Eswatini (Swaziland)', 2, 'most'),
    ('Eswatini (Swaziland)', 3, 'some'),
    ('Eswatini (Swaziland)', 4, 'some'),
    ('Eswatini (Swaziland)', 5, 'all'),
    ('Eswatini (Swaziland)', 8, 'some'),
    ('Eswatini (Swaziland)', 9, 'most'),
    ('Ethiopia', 1, 'some'),
    ('Ethiopia', 2, 'most'),
    ('Ethiopia', 3, 'some'),
    ('Ethiopia', 4, 'some'),
    ('Ethiopia', 5, 'all'),
    ('Ethiopia', 7, 'all'),
    ('Ethiopia', 8, 'some'),
    ('Ethiopia', 9, 'most'),
    ('Falkland Islands (Islas Malvinas)', 2, 'most'),
    ('Falkland Islands (Islas Malvinas)', 3, 'some'),
    ('Falkland Islands (Islas Malvinas)', 5, 'all'),
    ('Falkland Islands (Islas Malvinas)', 9, 'most'),
    ('Faroe Islands', 2, 'some'),
    ('Faroe Islands', 3, 'some'),
    ('Faroe Islands', 5, 'all'),
    ('Faroe Islands', 8, 'some'),
    ('Fiji', 2, 'most'),
    ('Fiji', 3, 'some'),
    ('Fiji', 5, 'all'),
    ('Fiji', 9, 'most'),
    ('Finland', 2, 'some'),
    ('Finland', 3, 'some'),
    ('Finland', 5, 'all'),
    ('Finland', 8, 'some'),
    ('France', 2, 'some'),
    ('France', 3, 'some'),
    ('France', 5, 'all'),
    ('France', 8, 'some'),
    ('French Guiana', 10, 'all'),
    ('French Guiana', 2, 'most'),
    ('French Guiana', 3, 'some'),
    ('French Guiana', 4, 'some'),
    ('French Guiana', 5, 'all'),
    ('French Guiana', 8, 'some'),
    ('French Guiana', 9, 'most'),
    ('French Polynesia', 2, 'most'),
    ('French Polynesia', 3, 'some'),
    ('French Polynesia', 5, 'all'),
    ('French Polynesia', 9, 'most'),
    ('Gabon', 10, 'all'),
    ('Gabon', 2, 'most'),
    ('Gabon', 3, 'some'),
    ('Gabon', 4, 'most'),
    ('Gabon', 5, 'all'),
    ('Gabon', 8, 'some'),
    ('Gabon', 9, 'most'),
    ('Gambia', 10, 'most'),
    ('Gambia', 2, 'most'),
    ('Gambia', 3, 'some'),
    ('Gambia', 4, 'most'),
    ('Gambia', 5, 'all'),
    ('Gambia', 8, 'some'),
    ('Gambia', 9, 'most'),
    ('Georgia', 2, 'most'),
    ('Georgia', 3, 'some'),
    ('Georgia', 5, 'all'),
    ('Georgia', 8, 'some'),
    ('Germany', 2, 'some'),
    ('Germany', 3, 'some'),
    ('Germany', 5, 'all'),
    ('Germany', 8, 'some'),
    ('Ghana', 1, 'some'),
    ('Ghana', 10, 'all'),
    ('Ghana', 2, 'most'),
    ('Ghana', 3, 'some'),
    ('Ghana', 4, 'most'),
    ('Ghana', 5, 'all'),
    ('Ghana', 7, 'all'),
    ('Ghana', 8, 'some'),
    ('Ghana', 9, 'most'),
    ('Gibraltar', 2, 'some'),
    ('Gibraltar', 3, 'some'),
    ('Gibraltar', 5, 'all'),
    ('Gibraltar', 8, 'some'),
    ('Greece', 2, 'some'),
    ('Greece', 3, 'some'),
    ('Greece', 5, 'all'),
    ('Greece', 8, 'some'),
    ('Greenland', 2, 'some'),
    ('Greenland', 3, 'some'),
    ('Greenland', 5, 'all'),
    ('Greenland', 8, 'some'),
    ('Grenada', 2, 'most'),
    ('Grenada', 3, 'some'),
    ('Grenada', 5, 'all'),
    ('Grenada', 8, 'some'),
    ('Grenada', 9, 'most'),
    ('Antigua and Barbuda', 2, 'most'),
    ('Antigua and Barbuda', 3, 'some'),
    ('Antigua and Barbuda', 5, 'all'),
    ('Antigua and Barbuda', 8, 'some'),
    ('Antigua and Barbuda', 9, 'most'),
    ('Guadeloupe', 2, 'most'),
    ('Guadeloupe', 3, 'some'),
    ('Guadeloupe', 5, 'all'),
    ('Guadeloupe', 8, 'some'),
    ('Guadeloupe', 9, 'most'),
    ('Guam', 2, 'most'),
    ('Guam', 3, 'some'),
    ('Guam', 9, 'most'),
    ('Guatemala', 2, 'most'),
    ('Guatemala', 3, 'some'),
    ('Guatemala', 4, 'some'),
    ('Guatemala', 5, 'all'),
    ('Guatemala', 8, 'some'),
    ('Guatemala', 9, 'most'),
    ('Guinea', 10, 'most'),
    ('Guinea', 2, 'most'),
    ('Guinea', 3, 'some'),
    ('Guinea', 4, 'most'),
    ('Guinea', 5, 'all'),
    ('Guinea', 8, 'some'),
    ('Guinea', 9, 'most'),
    ('Guinea-Bissau', 10, 'all'),
    ('Guinea-Bissau', 2, 'most'),
    ('Guinea-Bissau', 3, 'some'),
    ('Guinea-Bissau', 4, 'most'),
    ('Guinea-Bissau', 5, 'all'),
    ('Guinea-Bissau', 8, 'some'),
    ('Guinea-Bissau', 9, 'most'),
    ('Guyana', 10, 'most'),
    ('Guyana', 2, 'most'),
    ('Guyana', 3, 'some'),
    ('Guyana', 4, 'some'),
    ('Guyana', 5, 'all'),
    ('Guyana', 8, 'some'),
    ('Guyana', 9, 'most'),
    ('Haiti', 1, 'some'),
    ('Haiti', 2, 'most'),
    ('Haiti', 3, 'some'),
    ('Haiti', 4, 'most'),
    ('Haiti', 5, 'all'),
    ('Haiti', 8, 'some'),
    ('Haiti', 9, 'most'),
    ('Honduras', 2, 'most'),
    ('Honduras', 3, 'some'),
    ('Honduras', 4, 'some'),
    ('Honduras', 5, 'all'),
    ('Honduras', 8, 'some'),
    ('Honduras', 9, 'most'),
    ('Hong Kong SAR', 2, 'most'),
    ('Hong Kong SAR', 3, 'some'),
    ('Hong Kong SAR', 5, 'all'),
    ('Hong Kong SAR', 8, 'some'),
    ('Hong Kong SAR', 9, 'most'),
    ('Hungary', 2, 'most'),
    ('Hungary', 3, 'some'),
    ('Hungary', 5, 'all'),
    ('Hungary', 8, 'some');

-- SELECT * FROM recomendations;